### ISSUE TITLE
Allow web preview like appflow

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#222]
<img width="837" alt="CleanShot 2023-04-10 at 16 46 01@2x" src="https://user-images.githubusercontent.com/4084527/230913450-45b25087-3bfb-4aa2-8de5-fb8b9601018a.png">
Currently capgo app allow you to preview in your mobile, but it's not possible to preview in web.

**Comment by riderx** [comment]
With bundle not encoded it should be doable to display a preview of the app in an iframe.

**Comment by yuvrajjsingh0** [comment]
@riderx Do we want to show preview for all kinds of screens?? Web, iPhone and Android

**Comment by riderx** [comment]
i think that will bring a lot of complexity, just iPhone is enough.
Also this should be hidden on mobile of course

**Comment by yuvrajjsingh0** [comment]
Hi @riderx , I was just wondering if we have repo for capgo_app. I want to see how Test is implemented in App.

**Comment by riderx** [comment]
The data is store in a zip file in r2.
So I believe the browser has to unzip to display it.
Then it’s a basic spa any dummy example should work.
You can create an account in the app and then upload with the official CLI one random SPA code and try from there

**Comment by bikrantjajware** [comment]
Hello riderx,
i would like to work on this if this gets up for grabs :)

**Comment by riderx** [comment]
Not to to understand your comment, the ticket exist to create this feature. So you can’t see it because the feature has to be made

**Comment by WcaleNieWolny** [comment]
> question i should be able to preview the demo app in the capgo webapp at localhost:5173.

You are not missing anything - that is the capgo's webui

**Comment by WcaleNieWolny** [comment]
Since no one attempted this in a while I would like to try

/attempt #222

**Comment by WcaleNieWolny** [comment]
here is what I have been able to do:

https://github.com/Cap-go/capgo/assets/50914789/bfb08e22-5881-46ca-9d0e-45fe9cbb80e2

This however has some limitations

- This does not work on chrome [there is an open issue that would fix it but it's low priority](https://bugs.chromium.org/p/chromium/issues/detail?id=880768)
- It does not work with all apps. I had to replace `createWebHistory` with `createWebHashHistory` in the [demo app src/router/index.ts](https://github.com/Cap-go/demo-app/blob/main/src/router/index.ts) or otherwise this preview would not work
- I had to add a [service worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) meaning that it requires localhost or HTTPS to work
- I had to result to using pure javascript with pure CSS/HTML in some parts to make this work

Overall it only partially possible and very hacky. With little apps to test this I really cannot be sure that this will work with any other app then the demo one

**Comment by WcaleNieWolny** [comment]
I am happy to inform that I have fixed the chrome issue! Was not easy, but now it works quite well

I also made so that when you close the preview the app resets. This does not redownload the app and is near instantaneous when reopening the preview. Unfortunately I was not able to fix the version with `createWebHistory` meaning the demo app by default will not work. I do not get any error when running the default demo app so it's likely a bug that is deeply in vue router or something

https://github.com/Cap-go/capgo/assets/50914789/917f0a6f-d4f9-4a7d-9deb-fd606709381e

**Comment by riderx** [comment]
@WcaleNieWolny thanks for trying it !
Have you tried to do iframe with it ?
I believe that could solve the routing issue

**Comment by WcaleNieWolny** [comment]
@riderx Unfortunately but the behavior of an iframe is dependent on how you write to it. I currently use a `src=...` attribute but prevrious `srcdoc=HTML_SRC` and writing to iframe using JS both failed (service worker did not register properly for the iframe). I tried a lot of things with the iframe
