### ISSUE TITLE
Use the redis (cache system) to batch logs and device insert/update

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#336]
Currently, 60% of the request are these updates.
In the update and stats endpoint.
One idea is to register all request and do only one insert every x
In order to reduce the db load

**Comment by WcaleNieWolny** [comment]
I though about this. I do not really think this will scale. If we get another big client and then there is a lot of users postgress will still fail and the load will not get any smaller. If we do a batch request we COULD use redis as a choke point so that updates do not just crash the db (Because we limit the max inserts per 1 batch insert) but then we have a gigantic list of logs that are in redis that the user cannot access

**Comment by WcaleNieWolny** [comment]
Logs COULD be implemented in redis only, then they might be cheaper but I am not sure about the migration. How would we migrate thousand of logs from PostgreSQL into redis? Is it even worth to migrate?

**Comment by riderx** [comment]
I imagined migrate many time, in timescales influx db etc, but that requires to rewrite a lot of things to let the user still explore his logs.
That why I imagined batch update in redis to reduce the charge of the db.
If you know a solution for timeserie data cost effective with scaling price.
I can bounty the whole migration of it.
I saw upstash has kafka that could be interesting as well

**Comment by riderx** [comment]
Close in favor of #460
