### ISSUE TITLE
Add backend test for Update endpoint

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#358]
The goal is to have test in update endpoint with exhaustive test suit.
This endpoint is the most important of Capgo so it should be well tested

**Comment by ologbonowiwi** [comment]
Can you describe some of the test TO-DOs to start wth @riderx?

**Comment by WcaleNieWolny** [comment]
I will be attempting this.
Here is how I see this:
1. I create a new deno program that will be an end to end test runner for supabase functions
2. This runner will start `supabase functions  serve`
3. It will connect to supabase (so that tests can access the db)
4. I will start running tests without setting up redis
5. If any test fails it will exit with status code 1
6. It will restart `supabase functions serve` and add redis env variables
7. It will rerun all tests (this time with redis env variables)
8. (OPTIONALLY) if env variables were passed for [upstash](https://upstash.com/) it will again restart `supabase functions serve` and set env variables for redis upstash
9. It will rerun all tests (this time with redis upstash)

Here is what I already have:

![image](https://github.com/Cap-go/capgo/assets/50914789/478b6daa-eb97-4af9-bcd8-400f14243385)
![image](https://github.com/Cap-go/capgo/assets/50914789/26b64e1b-cb38-435c-9712-7a90bf2ad4eb)


/attempt #358
