### ISSUE TITLE
Allow select for major or minor for security 

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#360]
**Describe the bug/issue**
Currently we check by default if a major bump in version happened to disable update.
This behavior is used for native code change to prevent install update on device who doesn’t have the native code.
Over time I saw many complaints about doing a major bump for something final users don’t care.
Even if the display version can be different in App Store it seems annoying.

So one change who could be nice is to allow capgo user to set how disable work.
- major 
- minor
- version number 
- None

So The current behavior is “major”, minor will be check if the minor coming from device ( 2 in 1.2.3) is equal or above the latest in the channel.

version number will use the min version send as metadata in the upload step( cli should be modified as well), this version has to be displayed in the UI, if this data is missing and this setting is active, it will use it’s own number as min number.

an none will be no check, same as we disable the feature currently.

this settings should be set from the UI or the CLI.

By default the behavior should be major, and migration script should be provided to migrate all users.

**Comment by WcaleNieWolny** [comment]
> if the minor coming from device ( 2 in 1.2.3) is equal or above the latest in the channel.

If I understand correctly this will be exactly the same as `major` but instead of checking the first number it will check the second one? Like if you are in `1.1.2` and there is an update to `1.2.3` it will disallow this update?

> it will use it’s own number as min number

I do not understand this. If the minimum version for the update `1.3.5` is `1.3.0` for example then this makes a lot of sense but if that metadata does not exists then what is the minimum version? We could REQUIRE the min version to be set when enabling this setting. We would prompt the user with sth like `The minimum version for current bundle is not set, please set the minimum version for latest bundle (${BUNDLE NUMBER})`. Let me know how do you see it

**Comment by WcaleNieWolny** [comment]
Here is how the select looks:
![image](https://github.com/Cap-go/capgo/assets/50914789/d847750e-0009-49cd-a619-d85e1a8200d4)

Unfortunately the look of this select is browser depended as the `option` tag is styled differently in chrome and in firefox and styling it behaves differently between browser. Is that okay or do you want this to always look the same?

**Comment by WcaleNieWolny** [comment]
I am giving up on this. If someone wants to take this my changes are available [here](https://github.com/WcaleNieWolny/capgo/tree/selectable_disallow)

**Comment by WcaleNieWolny** [comment]
Since no one took this I will be reattempting this

**Comment by WcaleNieWolny** [comment]
![image](https://github.com/Cap-go/capgo/assets/50914789/e3d8527a-0fa8-493f-9400-5ee3e30e79dc)

@ridex I have added a system where if the metadata is not present and this version number is on then there will be a warning displayed. Do you like how this looks?
