### ISSUE TITLE
As an org member who is in paid plan I still see trial banner.

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#526]
When i switch to org who has paid plan i shouldn't see the trial banner of my other org.
![image](https://github.com/Cap-go/capgo/assets/4084527/21817a33-3a09-45f3-8dd9-786aeb0e3232)

**Comment by Min2who** [comment]
/attempt #526
can i get assigned?

**Comment by WcaleNieWolny** [comment]
Before attempting this, please provide an idea on how you are going to solve this issue. For some context, here is the situation:

Here is the situation:

 - User A invited user B to org
 - User B has purchased a plan
 - User A i still on trial, but owns all the apps
 - User's A trial runs out, now he cannot use capgo as capgo does not use the plan from user B
 
 Here are some problems to consider in your solution:
 - An org might consist of multiple paid users. (Let's say user A invites user C. User C has a paid plan. Now, both user C and B have paid plans. What happens now?)
  - How do you warn user B that joining will cause user A to use his plan?
  - How do we redesign the payment system without making it a total mess to solve this issue?

**Comment by WcaleNieWolny** [comment]
Here is the solution I propose, please note that this is just an idea from someone who implemented the org system. @riderx has the final say in the matter

 - Make the billing system org based. Here is what I mean by that:
 
 - Each org should have it's own billing section. If you are invited to more then 1 org, you can use the `OrganizationDropdown` to change the billing section.
  - A new role should be create. `Super admin`. This will allow for changing the billing (the documentation should be changed accordingly)
  - The billing popout should be removed/not shown from the main dashboard. We can just say `trail over`/`billing issue` in apps table.
  
  - The billing popout should be shown ONLY when you click on the app
  
  Here is what I mean
  
![image](https://github.com/Cap-go/capgo/assets/50914789/1b952611-0845-40a1-b2ca-e0ac8def81ad)

 - The element nr 1 should NEVER be shown on this main dashboard
 - After clicking on the app (`nr 2`) you should be able to see this billing popout (see next screenshot)
 - In the area (`nr 3`) a new column should be created. There we can state the state of the billing (`trail over`/`billing issue`)
 
 Once you click on the app this billing popout should be visible/stay as is

 
![image](https://github.com/Cap-go/capgo/assets/50914789/82d4bcd5-0c41-4f59-a176-4a3cc25c0568)

 - The billing setting should be moved to the orgs settings, instead of the user settings

**Comment by kremedev** [comment]
> Before attempting this, please provide an idea on how you are going to solve this issue. For some context, here is the situation:
> 
> Here is the situation:
> 
> * User A invited user B to org
> * User B has purchased a plan
> * User A i still on trial, but owns all the apps
> * User's A trial runs out, now he cannot use capgo as capgo does not use the plan from user B
> 
> Here are some problems to consider in your solution:
> 
> * An org might consist of multiple paid users. (Let's say user A invites user C. User C has a paid plan. Now, both user C and B have paid plans. What happens now?)
> * How do you warn user B that joining will cause user A to use his plan?
> * How do we redesign the payment system without making it a total mess to solve this issue?
> 
> @anshumanjaiswal @atulkrs

I didn't see this. I'm sorry. I just made a fix for org owner who has paid plan case.

**Comment by riderx** [comment]
Hey @WcaleNieWolny i agree a rewrite of the org billing could be a good idea but I’m not sure to understand why you think about so many changes.

i think we can fix the current situation without much changes.
And then later attach billing to org

one user has only one org he own and that the only billing he can access of.
So there no case of user A or B etc.
The one who own dictate the behavior.
This already the case, a user cannot pay for more than one org because he can only own only one anyway.
So there only a check of the plan of the org of the org owner to check that it, same in the CLI.

in the future for me your concern is still not valid as the we will still have only one org own by user in step 1.
So all stay same only in backend we will attach billing to orgs and apps to orgs instead of the main user.

then for the UI change only the billing section should move to org tab.
There rest shouldn’t change, the trial banner should display on home, but depend on what org is selected.

**Comment by WcaleNieWolny** [comment]
@riderx Fixing the CLI upload issue is important, but what we have now is a miscommunication/lack of docs. Right now a user has purchased a plan thinking it would affect the orgs that he is invited to. That did not happen, so we had to award a plan manually to the org owner. A solution to this issue could be to just show a popout saying "purchasing a plan will not affect the orgs you are invited to" and a fixed CLI. Then we can attach billing to orgs

**Comment by riderx** [comment]
@WcaleNieWolny i'm not sure that the feedback of the user we got.
For what i understand one users has paid and invit user 2 and user 2 cannot send update because he doesn't plan where it shouldn't since user 1 has one for his org.
The case you talk about is a egde case of thinking i believe will not happen often
