### ISSUE TITLE
use TRPC in hono 

### ISSUE THREAD

**Issue by riderx** [Cap-go/capgo#741]
The goal is to make any api call be fully types as we have for supabase:
https://github.com/honojs/middleware/tree/main/packages/trpc-server

**Comment by WcaleNieWolny** [comment]
This is NOT easy. I have attempted to do this briefly and I have failed completely. It's likely doable for the frontend but it's almost impossible to do for the CLI due to the fact that we have 2 repos. It also would require us to figure out how to use the middleware for TRPC with supabase which will not be easy.

**Comment by riderx** [comment]
Will not do
